first part of the task done
less08/jv-create-annotation pull request #2
Opened 2021-01-08 20:35 UTC by less08

2021-01-08 22:00 UTC, vicire requested changes

2021-01-08 22:00 UTC, vicire commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            if (command.equalsIgnoreCase("q")) {
make "q" constant

2021-01-08 22:00 UTC, vicire commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +                String[] betData = command.split(" ");
Same with " "

2021-01-08 22:00 UTC, vicire commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +                int value = Integer.parseInt(betData[0]);
Magic number here and under

2021-01-08 22:00 UTC, vicire commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            if (command.equalsIgnoreCase("q")) {
Same as in handleBet

2021-01-08 22:00 UTC, vicire commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            } catch (NumberFormatException e) {
What happened if we enter 1 String?

2021-01-08 22:00 UTC, vicire commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            betDao.addBet(bet);
Do we need to add null in storage?

2021-01-08 22:00 UTC, vicire commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +                User user = new User(name,sport);
What happened if we enter 1 or 3 Strings in command line?

2021-01-10 21:48 UTC, Max-Pochepets approved these changes

2021-01-10 21:48 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +                }
we could have just add another `IndexOutOfBound` exception to `catch` block

2021-01-10 21:48 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            }
same here

2021-01-11 07:59 UTC, RomanDubovskyi approved these changes

2021-01-11 07:59 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            System.out.println(bet == null ? null : bet.toString());
```suggestion
            System.out.println(bet);
```

2021-01-11 09:43 UTC, merged